export const INDICATOR_INFO = {
  ALT: {
    key: 'ALT',
    name: '丙氨酸氨基转移酶',
    shortName: 'ALT',
    unit: 'U/L',
    normalRange: { min: 7, max: 40 },
    description: '主要存在于肝细胞中，是反映肝细胞损伤最敏感的指标之一。',
    clinicalMeaning: 'ALT升高提示肝细胞受损，可见于病毒性肝炎、脂肪肝、酒精性肝病等。',
  },
  AST: {
    key: 'AST',
    name: '天冬氨酸氨基转移酶',
    shortName: 'AST',
    unit: 'U/L',
    normalRange: { min: 13, max: 40 },
    description: '广泛存在于肝脏、心肌、骨骼肌等组织中。',
    clinicalMeaning: 'AST升高可见于肝脏疾病、心肌梗死、肌肉损伤等。AST/ALT比值对诊断有辅助意义。',
  },
  ALP: {
    key: 'ALP',
    name: '碱性磷酸酶',
    shortName: 'ALP',
    unit: 'U/L',
    normalRange: { min: 44, max: 147 },
    description: '主要来源于肝脏和骨骼，反映胆汁淤积和骨骼疾病。',
    clinicalMeaning: 'ALP升高提示胆汁淤积、胆管阻塞、骨骼疾病或肝脏占位性病变。',
  },
  GGT: {
    key: 'GGT',
    name: 'γ-谷氨酰转移酶',
    shortName: 'GGT',
    unit: 'U/L',
    normalRange: { min: 8, max: 61 },
    description: '主要来源于肝胆系统，对酒精性肝损伤高度敏感。',
    clinicalMeaning: 'GGT升高见于酒精性肝病、胆道疾病、脂肪肝等。是酗酒的敏感指标。',
  },
  TBIL: {
    key: 'TBIL',
    name: '总胆红素',
    shortName: 'TBIL',
    unit: 'μmol/L',
    normalRange: { min: 3.4, max: 17.1 },
    description: '胆红素是血红蛋白分解代谢的产物，通过肝脏处理后排出体外。',
    clinicalMeaning: 'TBIL升高（黄疸）可见于溶血、肝细胞损伤、胆道阻塞等。',
  },
  DBIL: {
    key: 'DBIL',
    name: '直接胆红素',
    shortName: 'DBIL',
    unit: 'μmol/L',
    normalRange: { min: 0, max: 6.8 },
    description: '又称结合胆红素，已在肝脏与葡萄糖醛酸结合，可直接从肾脏排出。',
    clinicalMeaning: 'DBIL升高为主提示肝细胞性或梗阻性黄疸（肝内或肝外胆汁淤积）。',
  },
  IBIL: {
    key: 'IBIL',
    name: '间接胆红素',
    shortName: 'IBIL',
    unit: 'μmol/L',
    normalRange: { min: 1.7, max: 10.2 },
    description: '又称非结合胆红素，未经肝脏处理，不溶于水。',
    clinicalMeaning: 'IBIL升高为主提示溶血性黄疸或Gilbert综合征等遗传性胆红素代谢异常。',
  },
  ALB: {
    key: 'ALB',
    name: '白蛋白',
    shortName: 'ALB',
    unit: 'g/L',
    normalRange: { min: 35, max: 55 },
    description: '由肝脏合成，是血浆中含量最多的蛋白质，反映肝脏合成功能。',
    clinicalMeaning: 'ALB降低提示肝脏合成功能下降，见于慢性肝病、肝硬化、营养不良等。',
  },
  GLB: {
    key: 'GLB',
    name: '球蛋白',
    shortName: 'GLB',
    unit: 'g/L',
    normalRange: { min: 20, max: 40 },
    description: '包括多种免疫球蛋白，参与机体免疫防御功能。',
    clinicalMeaning: 'GLB升高见于慢性炎症、自身免疫性疾病、慢性肝病等。',
  },
  TP: {
    key: 'TP',
    name: '总蛋白',
    shortName: 'TP',
    unit: 'g/L',
    normalRange: { min: 65, max: 85 },
    description: '血浆中所有蛋白质的总和，包括白蛋白和球蛋白。',
    clinicalMeaning: 'TP降低见于肝脏合成功能下降、营养不良、肾病综合征等。',
  },
  AG: {
    key: 'AG',
    name: '白球比值',
    shortName: 'A/G',
    unit: '',
    normalRange: { min: 1.2, max: 2.4 },
    description: '白蛋白与球蛋白的比值，反映肝功能和免疫状态。',
    clinicalMeaning: 'A/G比值倒置（<1.0）提示慢性肝病、肝硬化或免疫异常。',
  },
}

export const RISK_LEVELS = {
  Normal: {
    key: 'Normal',
    label: '正常',
    range: [0, 30],
    color: '#10b981',
    bgColor: 'bg-emerald-100',
    textColor: 'text-emerald-800',
    darkBgColor: 'dark:bg-emerald-900/30',
    darkTextColor: 'dark:text-emerald-300',
    icon: '✅',
    description: '各项指标均在正常范围内，肝脏功能良好。',
  },
  Mild: {
    key: 'Mild',
    label: '轻度异常',
    range: [30, 60],
    color: '#f59e0b',
    bgColor: 'bg-amber-100',
    textColor: 'text-amber-800',
    darkBgColor: 'dark:bg-amber-900/30',
    darkTextColor: 'dark:text-amber-300',
    icon: '⚠️',
    description: '部分指标轻微偏高，建议调整生活方式，定期复查。',
  },
  Moderate: {
    key: 'Moderate',
    label: '中度异常',
    range: [60, 80],
    color: '#f97316',
    bgColor: 'bg-orange-100',
    textColor: 'text-orange-800',
    darkBgColor: 'dark:bg-orange-900/30',
    darkTextColor: 'dark:text-orange-300',
    icon: '🔶',
    description: '多项指标异常，建议及时就医进行进一步检查。',
  },
  Severe: {
    key: 'Severe',
    label: '重度异常',
    range: [80, 100],
    color: '#ef4444',
    bgColor: 'bg-red-100',
    textColor: 'text-red-800',
    darkBgColor: 'dark:bg-red-900/30',
    darkTextColor: 'dark:text-red-300',
    icon: '🚨',
    description: '多项指标严重偏离正常值，请立即就医。',
  },
}

export const ALLOWED_FILE_TYPES = ['application/pdf', 'image/jpeg', 'image/png']
export const MAX_FILE_SIZE_MB = 20
